<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo esc_html( $template['label'] ?: strtoupper( $template['key'] ) ); ?></title>
    <style>
        body { font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; margin: 40px; line-height: 1.6; color: #222; }
        header { border-bottom: 2px solid #111; margin-bottom: 24px; padding-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; }
        th { width: 28%; text-transform: capitalize; color: #555; }
        .meta { font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <header>
        <h1><?php echo esc_html( $template['label'] ?: strtoupper( $template['key'] ) ); ?></h1>
        <p class="meta">
            <?php
            printf(
                /* translators: 1: author name, 2: datetime */
                esc_html__( 'Generated by %1$s on %2$s', 'catlaq-online-expo' ),
                esc_html( $generated['name'] ?? '' ),
                esc_html( $generated['at'] ?? '' )
            );
            ?>
        </p>
    </header>

    <?php if ( ! empty( $template['description'] ) ) : ?>
        <p><?php echo esc_html( $template['description'] ); ?></p>
    <?php endif; ?>

    <?php if ( ! empty( $auto_fields ) ) : ?>
        <h2><?php esc_html_e( 'Auto Fields', 'catlaq-online-expo' ); ?></h2>
        <table>
            <tbody>
            <?php foreach ( $auto_fields as $field => $value ) : ?>
                <tr>
                    <th><?php echo esc_html( ucwords( str_replace( '_', ' ', $field ) ) ); ?></th>
                    <td>
                        <?php
                        if ( is_array( $value ) ) {
                            echo esc_html( wp_json_encode( $value ) );
                        } else {
                            echo esc_html( (string) $value );
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if ( ! empty( $payload ) ) : ?>
        <h2><?php esc_html_e( 'Payload', 'catlaq-online-expo' ); ?></h2>
        <pre><?php echo esc_html( wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE ) ); ?></pre>
    <?php endif; ?>
</body>
</html>
